### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by LngWork** [ParvulaCMS/parvula#15]
Very good job with this  project!

Suggested enhancement: include SEO

Minimum function could be:
1 - a place to put robot.txt
2 - an auto generated sitemap.xml with first level of menu

**Comment by BafS** [comment]
Thanks !
Yes, good ideas. I will work on it for the next release.

**Comment by BafS** [comment]
I've add `robots.txt` but to generate the sitemap I prefer to do a plugin so Parvula can stay light :)
