### ISSUE TITLE
I can't access to the administration page.

### ISSUE THREAD

**Issue by CamTosh** [ParvulaCMS/parvula#16]
I have a 404 in `/admin`. 

On `/plugins/Admin/main.php` I have `Undefined variable: configAdmin` in error.

Thank's to check this issue :)

**Comment by BafS** [comment]
I just tried with a fresh install and everything seem ok, what is you PHP version ? 
Is it possible to have more detail about this error please (the stack trace).

Thanks

**Comment by BafS** [comment]
I close this issue due to inactivity.
