### ISSUE TITLE
Cannot edit from admin panel

### ISSUE THREAD

**Issue by lowercasename** [ParvulaCMS/parvula#17]
I'm sure this is some sort of permissions-based problem which I simply don't know how to solve, but I can't edit any files from within the admin panel - the title bar flashes red when I do. I've set the pages directory to 755.

**Comment by BafS** [comment]
Are you able to create a page from the admin panel and then edit the page ?
Does it works if you chmod recursively ? `chmod -R 777` (try 777 to be sure)

**Comment by lowercasename** [comment]
If I `chmod -R 777` on the pages directory, editing works, and so does adding a new page after doing that.

**Comment by BafS** [comment]
Okay great, so it's a permission problem. Can I close this issue ?

**Comment by lowercasename** [comment]
No worries, thanks for the quick reply!
