### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by rodriguez-loic** [ParvulaCMS/parvula#18]
That's the kind of error apache returns when I try to access my Parvula project.

[Thu Jun 09 15:06:05.940034 2016] [:error] [pid 23555] [client XXXX] PHP Fatal error:  Cannot use $this as parameter in /xxx-PATH-xxx/Parvula/services.php on line 84

PHP 7.0.7 (cli) (built: May 25 2016 18:40:26) ( NTS )
Server version: Apache/2.4.20 (Unix)
Server built:   Apr 11 2016 10:04:04

Note: I replaced "Container $this" parameter to "$that" in this file and it seems to work correctly.

**Comment by BafS** [comment]
Hi !
Yes, I just fixed this error yesterday in the "dev" branch. Thanks for the feedback !

[#199ba82](https://github.com/ParvulaCMS/parvula/commit/199ba8206e9d0a6c34ac4421431302b57f318af2)

**Comment by BafS** [comment]
The new version has been released, it should works without problem with PHP 7.
