### ISSUE TITLE
I need help with the Parvula blog and with creating the blog posts

### ISSUE THREAD

**Issue by AlexL777** [ParvulaCMS/parvula#22]
Hello Developers,

I have problems with creating a blog post in Parvula CMS. I use the last Parvula version under PHP 7.0. Parvula Blogposts must have the slug with `_posts`. If I enter this slug so: `_posts-blogging-with-parvula`, then this post but does not appear in the blog at http://wpzweinull.ch/cms/parvula/_posts .

I recently uploaded the new files simply over the old files in the FTP account and have seen that there is a blog.

So I have been trying to write the first blog post for hours. A separate page is always displayed in the navigation. In the Parvula blog the blogpost unfortunately does not appear.

How do I have to do it right?

Thanks in advance.

P.S. This post for example at http://wpzweinull.ch/cms/parvula/_posts/blogging_mit_parvula_cms should appear in the blog, but it does not. Something I still make wrong or I do not see the error.

**Comment by BafS** [comment]
Thanks for the feedback.

That's strange, what is the meta of the `blogging_mit_parvula_cms.md` page (the yaml on top). Do you have the field `parent` ?

**Comment by AlexL777** [comment]
I thank you. You had taken me to control and in fact the metas were double, in lowercase and uppercase letters.

I have changed this now and see, it all works again :smile:

**Comment by BafS** [comment]
Okay perfect !
