### ISSUE TITLE
Several questions about the sub-menu in Parvula

### ISSUE THREAD

**Issue by AlexL777** [ParvulaCMS/parvula#23]
Hello Developers,

I would like to group some pages on my Parvula website and would like to create a submenu. For example, I need several pages under the menu item Home or Homepage.

But if I add this navigation to the header.html, there are errors in the frontend.

    <nav>
    <ul>
    <?php foreach ($pages() as $myPage) : ?>
    <?php if ($myPage->parent) : // Page WITH a parent ?>
    <li>
    <a href="<?= $baseUrl . $myPage->slug ?>"><?= $myPage->title ?></a>
    </li>
    <?php endif; ?>
    <?php endforeach; ?>
    </ul>
    </nav>

The errors look like this.

`Whoops \ Exception \ ErrorException (E_ERROR)
Function name must be a string`

`/themes/galaxy/_includes/header.html3`

Can you help me fix this?

Thanks in advance.

**Comment by rodriguez-loic** [comment]
Hello,

this was my navbar code, maybe it can help you:
`<?php foreach($pages as $myPage) { ?>
    <?php if (!$myPage->parent) { ?>
        <li class="nav-item <?= !$page->is($myPage) ?: 'active' ?>">
            <a class="nav-link" href="<?= $baseUrl . $myPage->slug ?>"><?= $myPage->title ?></a>
        </li>
    <?php } ?>
<?php } ?>`

**Comment by AlexL777** [comment]
Can you please show the code as a code. I do not see any code.

**Comment by rodriguez-loic** [comment]
It's correctly displayed for me. Maybe you need to refresh?

**Comment by AlexL777** [comment]
Ok, thank you, I test it right with me.

**Comment by AlexL777** [comment]
Ok, this works almost, but I need a slightly different navi. The main pages should be displayed. Now it looks like this at http://wpzweinull.ch/cms/parvula. Look at it, please.

**Comment by AlexL777** [comment]
I need this menu, but it generates an error.

    <nav>
    <ul>
        <?php foreach ($pages() as $myPage) : ?>
        <?php if (!$myPage->parent) : // Page WITHOUT a parent (main pages) ?>
        <li>
            <a href="<?= $baseUrl . $myPage->slug ?>"><?= $myPage->title ?></a>
            <?php if ($myPage->getChildren()) : // If the page have children ?>
                <ul>
                <?php foreach ($myPage->getChildren() as $myPage) : // List children ?>
                    <li><a href="<?= $baseUrl . $myPage->slug ?>"><?= $myPage->title ?></a></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </li>
        <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    </nav>`

**Comment by rodriguez-loic** [comment]
You are still using `pages()`...

**Comment by AlexL777** [comment]
The two braces I have now removed. Now the menu is displayed. Maybe I can still get it as a drop-down menu. That would be ideal for me.

**Comment by rodriguez-loic** [comment]
Well, for the dropdown you can use a CSS framework such as Foundation or Bootstrap, or do it your own way, there is a lot of resources on Internet to do it.

**Comment by BafS** [comment]
Thank you @rodriguez-loic for the answers.
