### ISSUE TITLE
If the Parvula-Admin-Password has to be entered in plaintext

### ISSUE THREAD

**Issue by AlexL777** [ParvulaCMS/parvula#24]
Hello Developers,

I explore a bit the Parvula CMS and wanted to know whether the password in the file `users.php` must be entered as Plaintext or encoded. As Plaintext it folds quite well and I can register well under **/admin** in the browser.

That's what I want to know, so I can tell my blog readers.

Thanks in advance.

**Comment by BafS** [comment]
Hi,

As it is written in [the user.php file](https://github.com/ParvulaCMS/parvula/blob/a866c3fefd97847ca153fdc07af0dc7211edc067/data/users/users.php#L7) password should be BCrypted but plain password also work.

For more info about BCrypt and how to hash a password: [`password_hash()`](https://secure.php.net/manual/en/function.password-hash.php)

**Comment by AlexL777** [comment]
Hi,
Thank you for quickly answering my question. I think I can leave it at the simple password.
