### ISSUE TITLE
Question: Will there be a search function for blog function in Parvula CMS in the future?

### ISSUE THREAD

**Issue by AlexL777** [ParvulaCMS/parvula#25]
Hello Developers,

I would like to ask if you will integrate a search function into Pavula CMS? If I imagine it so that over time all sorts of posts under `/_myposts` will arise. It would be interesting to know whether you planned it.

The search function on a Parvula website would be useful. Perhaps something like this will flow into the next Parvula releases.

Thanks in advance.

**Comment by BafS** [comment]
I did not plan to add a search function at the moment.
In the next version I will stabilise the API and the structure of Parvula, then I will see but it could also be a plugin. Feel free to create one if you are motivated !

I close the issue for the moment.
